<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetalleEgresosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('detalle_egresos')->insert(
            array(
                array(
                    "tipo_egreso" => "CANC. ANTICIPO FABRICACIÓN JOYERÍA",
                    "descripcion" => "CANCELACION FABRICACION ARGOLLAS CATALOGO REF VZAR053 TALLA 10 (5.93) TALLA 7 (5.1) FACTURA EMEV1611",
                    "subtotal" => "3.675.612,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "3.675.612,00",
                ),
                array(
                    "tipo_egreso" => "CANC. ANTICIPO FABRICACIÓN JOYERÍA",
                    "descripcion" => "CANCELACION FABRICACION CATALOGO ANILLO DAMA CON CIRCONES CRUZADO REF VZAM037 QUEDO DE 3,69 GRS FACTURA EMEV1589",
                    "subtotal" => "1.248.008,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.248.008,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 964 NRO. VENTA: EMEV1588",
                    "subtotal" => "1.095.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.095.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "PLAN SEPARE CANCELACIÓN PLAN SEPARE NRO: 965 NRO. VENTA: EMEV1579",
                    "subtotal" => "581.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "581.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 977 NRO. VENTA: EMEV1605",
                    "subtotal" => "845.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "845.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 982 NRO. VENTA: EMEV1610",
                    "subtotal" => "450.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "450.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 985 NRO. VENTA: EMEV1615",
                    "subtotal" => "474.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "474.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 986 NRO. VENTA: EMEV1577",
                    "subtotal" => "845.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "845.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 988 NRO. VENTA: EMEV1600",
                    "subtotal" => "2.632.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "2.632.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 989 NRO. VENTA: EMEV1594",
                    "subtotal" => "214.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "214.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 990 NRO. VENTA: EMEV1598",
                    "subtotal" => "422.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "422.000,00",
                ),
                array(
                    "tipo_egreso" => "CANCELACION PLAN SEPARE",
                    "descripcion" => "CANCELACIÓN PLAN SEPARE NRO: 994 NRO. VENTA: EMEV1604",
                    "subtotal" => "870.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "870.000,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A EMPLEADOS",
                    "descripcion" => "CXC A EMPLEADO JAMES PAEZ- PRESTAMOS ENCHAPE CONT 96520",
                    "subtotal" => "154.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "154.700,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A EMPLEADOS",
                    "descripcion" => "CXC A EMPLEADO JHONATA ACOSTA- PRESTAMO ENCHAPE CONT 96281",
                    "subtotal" => "35.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "35.700,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CXC A FINANCREA SAS CREDITO 87100 FACTURA VENTA EMEV1586",
                    "subtotal" => "480.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "480.000,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CXC A NEGOCIOS MARISCAL SERVICIOS COMERCIALES FACTURA ELECTRONICA EMEV1597",
                    "subtotal" => "623.307,11",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "623.307,11",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELACION CXP DESTAPE JOYAS JULIO 2023 FACTURA ELECTRONICA EVIV 10956",
                    "subtotal" => "1.256.304,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.256.304,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELACION CXP REFACCION JOYERIA JUNIO 2023 FACTURA ELECTRONICA EVIV 11054",
                    "subtotal" => "79.968,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "79.968,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A BROTHERHOOD SAS FACTURA 108",
                    "subtotal" => "505.572,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "505.572,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A CONSEGUR SAS FACTURA 8964",
                    "subtotal" => "1.071.813,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.071.813,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A DENIM BLUE JEANS SAS FACTURA 12359",
                    "subtotal" => "937.958,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "937.958,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A ELKIN ELIECER SALAZAR A FACTURA 272",
                    "subtotal" => "360.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "360.000,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A M.R LUXURY SAS FACTURA 84",
                    "subtotal" => "2.598.067,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "2.598.067,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A MARIA ELVIA SANTA FLOREZ FACTURA 2796",
                    "subtotal" => "214.200,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "214.200,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A MARIA PAULINA TIRADO RESTREPO FACTURA 339",
                    "subtotal" => "5.432.606,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "5.432.606,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A RED DE SERVICIOS INTEGRALES DE COLOMBIA SAS FACTURA 7437",
                    "subtotal" => "791.782,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "791.782,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "CANCELADO A CXP A TECNOINCOL SAS FACTURA 10433",
                    "subtotal" => "247.911,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "247.911,00",
                ),
                array(
                    "tipo_egreso" => "CUENTA POR COBRAR: A TERCEROS",
                    "descripcion" => "PAGO A CXP A IMPOINVERSIONES FACTURA EEV3192",
                    "subtotal" => "59.959,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "59.959,00",
                ),
                array(
                    "tipo_egreso" => "OPERACIONES EFECTY",
                    "descripcion" => "COMPENSACION EFECTY DEL 20 AL 26 OCTUBRE 2023 B/COLOMBIA REG OPERACION 107295736",
                    "subtotal" => "1.601.343,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.601.343,00",
                ),
                array(
                    "tipo_egreso" => "OPERACIONES EFECTY",
                    "descripcion" => "COMPENSACION EFECTY DEL 29 SEPT AL 05 OCTUBRE 2023 B/COLOMBIA REG OPERACION 240719324",
                    "subtotal" => "820.458,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "820.458,00",
                ),
                array(
                    "tipo_egreso" => "OPERACIONES EFECTY",
                    "descripcion" => "COMPENSACION EFECTY DEL 06 AL 12 OCTUBRE 2023 B/COLOMBIA REG OPERACION 628221156",
                    "subtotal" => "989.010,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "989.010,00",
                ),
                array(
                    "tipo_egreso" => "OPERACIONES EFECTY",
                    "descripcion" => "COMPENSACION EFECTY DEL 13 AL 19 OCTUBRE 2023 B/COLOMBIA REG OPERACION 805450174",
                    "subtotal" => "397.963,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "397.963,00",
                ),
                array(
                    "tipo_egreso" => "SRVCIO: REFACCIÓN",
                    "descripcion" => "REFACCION JOYAS JULIO 2023 FACTURA
                    ELECTRONICA EVIV 12109",
                    "subtotal" => "224.880,00",
                    "vlr_iva" => "42.727,00",
                    "vlr_rte_fte" => "8.995,00",
                    "vlr_rte_iva" => "6.409,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "252.203,00",
                ),
                array(
                    "tipo_egreso" => "TRANSFORMACIÓN DE ORO",
                    "descripcion" => "ANILLO GRADO CUENTA DE COBRO # 146",
                    "subtotal" => "193.050,00",
                    "vlr_iva" => "42.727,00",
                    "vlr_rte_fte" => "8.995,00",
                    "vlr_rte_iva" => "6.409,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "193.050,00",
                ),
                array(
                    "tipo_egreso" => "TRANSFORMACIÓN DE ORO",
                    "descripcion" => "DESTAPE DE JOYAS SEPT 2023 FACTURA ELECTRONICA EVIV 12012",
                    "subtotal" => "552.600,00",
                    "vlr_iva" => "104.994,00",
                    "vlr_rte_fte" => "22.104,00",
                    "vlr_rte_iva" => "15.749,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "619.741,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO EXCEDENTE ABONO SEPARADO 996 ID PAGO 2504 AUT 105521 MASTERCARD DB (900.000)",
                    "subtotal" => "500.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "500.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO ABONO SEPARADO ID 2501 # 995 AUT 111941 MASTERCARD DB",
                    "subtotal" => "550.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "550.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO EXCEDENTE FACTURA EMEV1590 AUT 604952 MASTERCARD DB (260.000)",
                    "subtotal" => "150.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "150.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEP10988 CONTRATO 96534 AUT 042249 MASTERCARD CR",
                    "subtotal" => "30.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "30.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEP11016 CONTRATO 96895 AUT 105312 MASTERCARD DB",
                    "subtotal" => "43.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "43.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEP11075 CONTRATO 95912 AUT 296173 VISA DB",
                    "subtotal" => "308.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "308.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1580 AUT 604337 MASTERCARD DB",
                    "subtotal" => "650.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "650.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1587 AUT 687270 VISA DB",
                    "subtotal" => "2.100.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "2.100.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1589 AUT 154324 MASTERCARD DB",
                    "subtotal" => "748.008,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "748.008,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1595 AUT 103919 MASTERCARD DB",
                    "subtotal" => "4.774.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "4.774.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1599 AUT 118252 VISA DB",
                    "subtotal" => "2.272.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "2.272.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURA EMEV1608 AUT 124106 MASTERCARD DB",
                    "subtotal" => "1.151.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.151.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURAS EMEP10935 (94098) EMEP10936 (94990) AUT 102817 MASTERCARD DB",
                    "subtotal" => "126.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "126.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-DATAFONO",
                    "descripcion" => "T.FONDOS PAGO FACTURAS EMEP11218 EMEP11219 CONTRATOS (95474-96459) AUT 255910 MASTERCARD CR",
                    "subtotal" => "65.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "65.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 91673, PRORROGA N°: 46645, SUCURSAL PAGO: 128",
                    "subtotal" => "156.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "156.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 91673, PRORROGA N°: 46830, SUCURSAL PAGO: 128",
                    "subtotal" => "78.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "78.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 93376, PRORROGA N°: 46851, SUCURSAL PAGO: 128",
                    "subtotal" => "150.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "150.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 94611, PRORROGA N°: 46614, SUCURSAL PAGO: 128",
                    "subtotal" => "77.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "77.700,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 94611, PRORROGA N°: 46804, SUCURSAL PAGO: 128",
                    "subtotal" => "77.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "77.700,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 96693, PRORROGA N°: 46565, SUCURSAL PAGO: 128",
                    "subtotal" => "50.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "50.000,00",
                ),
                array(
                    "tipo_egreso" => "TRASLADO DE FONDOS SALIDA-E-COMMERCE",
                    "descripcion" => "PAGO PRORROGA REALIZADA DESDE EL ECOMMERCE DATOS: CONTRATO N° 96693, PRORROGA N°: 46721, SUCURSAL PAGO: 128",
                    "subtotal" => "50.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "50.000,00",
                ),
                array(
                    "tipo_egreso" => "",
                    "descripcion" => "TOTAL: ",
                    "subtotal" => "47.287.179,11",
                    "vlr_iva" => "147.721,00",
                    "vlr_rte_fte" => "31.099,00",
                    "vlr_rte_iva" => "22.158,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "47.381.643,11",
                ),
            )
        );
    }
}

