<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetalleGastosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('detalle_gastos')->insert(
            array(
                array(
                    "tipo_egreso" => "ARRENDMTO: PROP RAIZ(LOCALES)",
                    "descripcion" => " ARRIENDO MES OCTUBRE 2023 (AGUIRRE) FACTURA ELECTRONICA FE1339",
                    "subtotal" => "2.791.875,00",
                    "vlr_iva" => "530.456,00",
                    "vlr_rte_fte" => "97.716,00",
                    "vlr_rte_iva" => "79.568,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "3.145.047,00",
                ),
                array(
                    "tipo_egreso" => "ARRENDMTO: PROP RAIZ(LOCALES)",
                    "descripcion" => "ARRIENDO MES OCTUBRE 2023 (CLAUDIA-ZONACENTRO) FACTURA ELECTRONICA ZCIE53529 COLTEFINANCIERA",
                    "subtotal" => "2.791.875,00",
                    "vlr_iva" => "530.456,00",
                    "vlr_rte_fte" => "97.716,00",
                    "vlr_rte_iva" => "79.568,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "3.145.047,00",
                ),
                array(
                    "tipo_egreso" => "COMISIÓN MASRED",
                    "descripcion" => "COMISION X LETRAS CAMBIO SEPTIEMBRE 2023 FACTURA ELECTRONICA FE 7655",
                    "subtotal" => "647.871,00",
                    "vlr_iva" => "123.095,00",
                    "vlr_rte_fte" => "71.266,00",
                    "vlr_rte_iva" => "18.464,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "681.236,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: LITOGRAFIA",
                    "descripcion" => "3 AVISOS ACRILICO (MISION-VISION OTROS) FACT 844",
                    "subtotal" => "42.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "42.000,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: LITOGRAFIA",
                    "descripcion" => "SELLOS EN MADERA (RESOLUCION-FACTURAS) FACTURA ELECTRONICA FE1343",
                    "subtotal" => "24.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "24.000,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: COMBUSTIBLE",
                    "descripcion" => "GASOLINA CORRIENTE (CRISTIAN CRUZ-MANIZALES) ENTREGA RESOLUCION FACT P381-835051",
                    "subtotal" => "50.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "50.000,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: ELEMENTOS CAFETERÍA IVA19%",
                    "descripcion" => "CONFITES HALLOWEEN FACTURA ELECTRONICA 2323",
                    "subtotal" => "32.941,00",
                    "vlr_iva" => "6.259,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "39.200,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: ELEMENTOS CAFETERÍA IVA5%",
                    "descripcion" => "AZUCAR FACTURA ELECTRONICA FE1 6688",
                    "subtotal" => "13.333,00",
                    "vlr_iva" => "667,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "14.000,00",
                ),


                array(
                    "tipo_egreso" => "COMPRAS: ELEMENTOS DE ASEO ",
                    "descripcion" => "ELEMENTOS ASEO FACTURA ELECTRONICA FE1 6688",
                    "subtotal" => "75.378,00",
                    "vlr_iva" => "14.322,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "89.700,00",
                ),
                array(
                    "tipo_egreso" => "COMPRAS: INSUMOS CONTRATACION Y VENTAS",
                    "descripcion" => "TESTER DE JOYERIA FACTURA ELECTRONICA MEDE 10504",
                    "subtotal" => "56.104,00",
                    "vlr_iva" => "10.660,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "66.764,00",
                ),

                array(
                    "tipo_egreso" => "COMPRAS: UTILES DE PAPELERÍA",
                    "descripcion" => "UTILES DE PAPELERIA FACTURA ELECTRONICA B70912",
                    "subtotal" => "68.571,00",
                    "vlr_iva" => "13.028,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "81.599,00",
                ),

                array(
                    "tipo_egreso" => "ESTUDIO DE COMPETENCIA",
                    "descripcion" => "RETROVENTA CONTRATO 49734",
                    "subtotal" => "37.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "37.000,00",
                ),

                array(
                    "tipo_egreso" => "GASTOS BANCARIOS: 4 X MIL",
                    "descripcion" => "RECLASIFICAR TRANSACCION CHEQUE 060 B/AGRARIO",
                    "subtotal" => "5.400,00",
                    "vlr_iva" => "1.026,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "6.426,00",
                ),
                array(
                    "tipo_egreso" => "GASTOS BANCARIOS: 4 X MIL",
                    "descripcion" => " RECLASIFICAR TRANSACCION CHEQUE 060 B/AGRARIO",
                    "subtotal" => "5.400,00",
                    "vlr_iva" => "1.026,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "6.426,00",
                ),
                array(
                    "tipo_egreso" => "GASTOS LEGALES: SANIDAD",
                    "descripcion" => "SERVICIO DE FUMIGACION CONTROL DE PLAGAS FACTURA ELECTRONICA FE-1381",
                    "subtotal" => "55.000,00",
                    "vlr_iva" => "10.450,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "65.450,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIO: LOGISTICA",
                    "descripcion" => "SERVICIO DE LOGISTICA FABRICACION SINDRI FACTURA EECV 3192",
                    "subtotal" => "50.386,00",
                    "vlr_iva" => "9.573,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "59.959,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIO: PARQUEADERO",
                    "descripcion" => "PARQUEADERO (CRISTIAN CRUZ-MANIZALES) ENTREGA RESOLUCION FACT 302626",
                    "subtotal" => "4.874,00",
                    "vlr_iva" => "926,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "5.800,00",
                ),


                array(
                    "tipo_egreso" => "SRVCIO: RESTAURANTE",
                    "descripcion" => "REFRIGERIO (SALIDA CAJERO VOTACION) FACT D17352930 - 931",
                    "subtotal" => "16.852,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "16.852,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIO: RESTAURANTE",
                    "descripcion" => "REFRIGERIO CAPACITACION HONESTIDAD - INTEGRIDAD",
                    "subtotal" => "24.300,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "24.300,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIO: RESTAURANTE",
                    "descripcion" => "REFRIGERIO CREDITO APROBADO (87100 - HEBER)",
                    "subtotal" => "14.444,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "14.444,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIO: RESTAURANTE",
                    "descripcion" => "SERVICIO DE COMEDOR (JAMES TURNO CAJERO) FACT A19022606",
                    "subtotal" => "11.574,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "11.574,00",
                ),
                array(
                    "tipo_egreso" => "SRVCIO: RESTAURANTE",
                    "descripcion" => "SERVICIO DE RESTAURANTE (JHONATAN-CAJERO)",
                    "subtotal" => "14.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "14.000,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO",
                    "descripcion" => "ACUEDUCTO $20.951 ALCANTARILLADO $15.288 ASEO $53.859 MES SEPTIEMBRE 2023 FACT 64759993",
                    "subtotal" => "90.098,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "90.098,00",
                ),
                array(
                    "tipo_egreso" => "SRVCIOS PUBLIC: CELULAR COORP. JOYERIA",
                    "descripcion" => "PLAN CELULAR CORPORATIVO FACTURA ELECTRONICA E 5739880752",
                    "subtotal" => "33.442,00",
                    "vlr_iva" => "6.354,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "39.796,00",
                ),
                array(
                    "tipo_egreso" => "SRVCIOS PUBLIC: CELULAR COORP. JOYERIA",
                    "descripcion" => "ENERGIA $930.739 ALUMBRADO PUBLICO $20.000 MES SEPTIEMBRE 2023 FACT 45472947",
                    "subtotal" => "950.739,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "950.739,00",
                ),


                array(
                    "tipo_egreso" => "SRVCIOS PUBLIC: INTERNET",
                    "descripcion" => "PLAN INTERNET MES SEPTIEMBRE 2023 REF DE PAGO 20811293614",
                    "subtotal" => "110.249,00",
                    "vlr_iva" => "20.947,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "131.196,00",
                ),

                array(
                    "tipo_egreso" => "SRVCIOS PUBLIC: TELEVISIÓN POR CABLE",
                    "descripcion" => "PLAN TV X CABLE MES OCTUBRE 2023 REF DE PAGO 20811293614",
                    "subtotal" => "52.400,00",
                    "vlr_iva" => "9.956,00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "62.356,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ADMIN DE RIESGOS LABORALES, ARL",
                    "descripcion" => "PAGO RIESGOS ARL SURA MES SEPTIEMBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "69.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "69.700,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: CAJA DE COMPENSACION FAMILIAR",
                    "descripcion" => "PAGO CAJA COMP FAMILIAR COMFENALCO MES SEPTIEMBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "531.700,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "531.700,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ENTIDADES PROMOTORAS DE SALUD EPS",
                    "descripcion" => "PAGO SALUD EPS SURA MES OCTUBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "92.100,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "92.100,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ENTIDADES PROMOTORAS DE SALUD EPS",
                    "descripcion" => "PAGO SALUD ASMET SALUD MES OCTUBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "81.900,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "81.900,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ENTIDADES PROMOTORAS DE SALUD EPS",
                    "descripcion" => "PAGO SALUD NUEVA EPS MES OCTUBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "76.100,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "76.100,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ENTIDADES PROMOTORAS DE SALUD EPS",
                    "descripcion" => "PAGO SALUD SANITAS MES OCTUBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "95.600,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "95.600,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: ENTIDADES PROMOTORAS DE SALUD EPS",
                    "descripcion" => "PAGO SALUD TOTAL EPS MES OCTUBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "186.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "186.000,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: FONDOS DE PENSIONES AFP",
                    "descripcion" => "PAGO PENSION COLPENSIONES MES SEPTIEMBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "551.400,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "551.400,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: FONDOS DE PENSIONES AFP",
                    "descripcion" => "PAGO PENSION PORVENIR MES SEPTIEMBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "1.192.000,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "1.192.000,00",
                ),
                array(
                    "tipo_egreso" => "SS PF: FONDOS DE PENSIONES AFP",
                    "descripcion" => "PAGO PENSION PROTECCION MES SEPTIEMBRE 2023 REF PAGO - PLANILLA 65971508 - 51527",
                    "subtotal" => "382.300,00",
                    "vlr_iva" => ",00",
                    "vlr_rte_fte" => ",00",
                    "vlr_rte_iva" => ",00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "382.300,00",
                ),
                array(
                    "tipo_egreso" => "",
                    "descripcion" => "TOTAL",
                    "subtotal" => "13.938.244,00",
                    "vlr_iva" => "1.781.651,00",
                    "vlr_rte_fte" => "367.951,00",
                    "vlr_rte_iva" => "249.743,00",
                    "vlr_rte_ica" => ",00",
                    "vlr_rte_cree" => ",00",
                    "valor" => "15.107.031,00",
                ),
            )
        );
    }
}
